<?php
/**
 * @file
 * Code for the Basic Ubercart Product feature.
 */

include_once 'basic_ubercart_product.features.inc';

/**
 * Implements hook_theme_registry_alter().
 *
 * Changes the print theme registry to use custom template while preserving
 * any overrides from themes.
 */
function basic_ubercart_product_theme_registry_alter(&$theme_registry) {
  // Defined path to current module.
  $module_path = drupal_get_path('module', 'basic_ubercart_product');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  // Itterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
    }
  }
}
