<?php
/**
 * @file
 * Code for the Basic Ubercart Categories feature.
 */

include_once 'basic_ubercart_categories.features.inc';

/**
 * Implements hook_views_data().
 */
function basic_ubercart_categories_views_data() {

  $data['views']['taxonom_description'] = array(
    'title' => t('Taxonomy Term Description'),
    'help' => t('If this is a taxonomy term page, the terms description.'),
    'area' => array(
      'handler' => 'views_handler_taxonomy_description',
    ),
  );

  return $data;
}
